#!/bin/sh
SBT_LAUNCH=/usr/local/Cellar/sbt/0.13.1/libexec/sbt-launch.jar
DEBUG_PORT=$1
SBT_ARGS=`echo "$@" | grep -oE "[^0-9].*"`

exec java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT} ${SBT_OPTS} -jar $SBT_LAUNCH
$SBT_ARGS
